Feature/#8 channel 객체 만들기
DeveloperRyou/ft_irc pull request #27
Opened 2023-05-25 13:29 UTC by ssoyeong-lee

freenode & limechat 기준 참고하여 작성.

`일단 참고용으로 풀리퀘합니다!`

### 슬랙 내용 외 추가된 내용
1. client_size: MODE +l 에 대한 내용, 현재 채널 접속 인원 수 저장
2. limit: MODE +l 에 대한 내용, 채널 최대 동시 접속 인원수 저장
3. broadcast 오버로딩: 인자에 client O -> 해당 클라이언트 제외 브로드캐스팅, X -> 모든 클라이언트에게 브로드캐스팅
4. getClientNameList(): 채널 JOIN 시 서버에서 클라이언트에게 해당 채널 참여 클라이언트 닉네임리스트 전송해준다.

### 생각해본 것들
1. ChannelMode::isValidMode함수에서 vector 개수 계산 함께 해주어야 할 듯...
2. 각 전송되는 메시지 앞 prefix: 보내는 서버나 클라이언트의 정보 담김 -> Server, Client class 안에 getPrefix() 구현되어야함.
3. mode() 함수 더 예쁘게 짜고 싶다...

2023-05-26 08:22 UTC, DeveloperRyou reviewed
1. subClient 에서 남은 클라이언트 수가 0면 에러를 throw 하는데, 이부분은 없어도 될것 같습니다. 결국에는 이 채널 인스턴스를 사용하는 부분에서 채널에 남아있는 클라 수 확인하고, 0이면 삭제처리를 해줘야하는데 parser에 구현되어야 할거 같네요.
2. mode 함수에서  +, - 파싱하는 부분들이 ChannelMode로 가면 깔끔해질 것 같네요. 그럼 문제가 channelmode 에서 modeparsing을 하면서 적함한 channel 속성을 바꿔주어야 하는데, 이부분은 생각해볼 법 합니다.

2023-05-27 12:09 UTC, ssoyeong-lee commented
# ChannelMode 변경에 따른 Channel 수정
- ch_mode 자료형 변경 & 해당 객체 메소드명 수정
- nickname으로 해당 채널에 가입한 클라이언트 찾는 함수 추가 findClient
- MODE -o 메시지 받았을 때 해당 클라이언트 모드를 OPER로 수정해주는 함수

살펴보시고 머지 해주세요!

2023-05-27 12:34 UTC, DeveloperRyou requested changes
1. 동적할당으로 모드들을 관리해주시고 있는데, Subclient 나 소멸자에서 delete 하는 로직이 안보입니다. 메모리 누수같은데, 1) 동적할당을 삭제해주시거나 2) 메모리 관리 (delete) 로직을 추가해주셔야 할거 같아요
2. 에러 메세지 포맷은 나중에 한번에  업데이트 하는거로 할까요? throw 하는 에러도 있고, send 하는 에러도 있고, 코드가 들어가 있는데도 있고, 없는데도 있어서 이건 나중에 통일하는게 좋아보입니다.
3. 나머지 메소드들은 좋아보입니다~
4.

2023-05-28 09:16 UTC, DeveloperRyou approved these changes

2023-05-28 09:16 UTC, merged